version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  db:
    image: postgres
    container_name: cegov_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
  web:
    build: .
    depends_on:
        - db
    container_name: cegov_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
     - DB_NAME=cegov
     - DB_USER=postgres
     - DB_HOST=db
     - DB_PORT=5432
     - DB_PASS=
     - HTTP_HOST=127.0.0.1,0.0.0.0
     - DEBUG=True
     - ADMIN_PATH=b72c0824
