version: '3'

volumes:
  postgres_data_dev: {}

services:
  db:
    image: postgres
    container_name: cegov_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
        - db
    container_name: cegov_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
     - DB_NAME=postgres
     - DB_USER=postgres
     - DB_HOST=db
     - DB_PORT=5432
     - DB_PASS=
     - HTTP_HOST=127.0.0.1,0.0.0.0,icef.localhost,qa-icef.localhost
     - DEBUG=True
     - ADMIN_PATH=b72c0824
     - DO_MIGRATE=True
     - DJANGO_LOG_LEVEL=DEBUG
     - RUN_DEBUG_MODE=True
